# Обработка исключительных ситуаций

**Исключения** - внештатные ситуации, которые происходят при работе программы.

`try {}` - пробный блок, в котором может возникнуть какая-то внештатная ситуация.

`throw` - оператор "выбрасывания" исключения

`catch (type data) {}` - блок, операторы которого вызываются в случае внештатной ситуации.

```cpp
class vect {
public:
	vect(int n);
private:
	float *p;
	int k;
};

vect::vect(int n): k(n) {
	if (n < 1) throw (n);
	p = new float[n];
	if (p == 0) throw ("Недостаточно памяти");
}

void f (int m) { // Защищённый код
	try { vect a(m), b(m); }
	catch (int n) { /* ... */ }
	catch (char* error) { /* ... */ }
}
```

## Перезапуск запущенного исключения

